name: Build and Push SmartDNS Image Commit 8bae7c1

on:
  push:
    branches: [ "main" ] # Only build when pushing to the main branch
  workflow_dispatch: # Allow manual trigger

env:
  # CHANGE: Rename the image according to your project
  IMAGE_NAME: smartdns-w-ui
  REGISTRY: ghcr.io
#GOARCH: ${{ matrix.goarch }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7

    steps:
      - name: Generate Date Tag
        id: date-tag # Assign an ID so that it can be accessed in other steps if necessary.
        run: echo "TAG_CURRENT=$(date +'v%Y%m%d')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      # CHANGES: Add QEMU for ARM architecture emulation
      # This is very important for cross-compilation on x86_64 runners.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Assumption that Dockerfile is in the root repo
          file: ./Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          build-args: |
            TARGETPLATFORM=${{ matrix.platform }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.TAG_CURRENT }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          # CHANGES: Enable cache to speed up subsequent builds
          # This will save the Docker layer, including the downloaded 'cargo' and 'npm' results.
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
